apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: cas-ggircs-ciip-2018-schema
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs-ciip-2018-schema:${GIT_BRANCH_NORM}
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    source:
      git:
        ref: ${GIT_BRANCH}
        uri: https://github.com/bcgov/cas-ggircs-ciip-2018.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: cas-ggircs-perl:${PERL_VERSION}
      type: Source
    triggers:
    - github:
        secret: cas-ggircs-ciip-2018-schema-github-trigger
      type: GitHub
    - generic:
        secret: cas-ggircs-ciip-2018-schema-generic-trigger
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange

parameters:

- description: Version of Perl image to be used (latest for now).
  displayName: Version of Perl Image
  name: PERL_VERSION
  required: true
  value: "latest"
- description: Git source code branch currently deployed.
  displayName: Git branch
  name: GIT_BRANCH
  required: true
- description: Git source code branch currently deployed, where slashes are replaced by dashes, to be able to use it in image tags.
  displayName: Git branch (normalized)
  name: GIT_BRANCH_NORM
  required: true
