apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template


parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true

envDefaults: &envDefaults
  env:
    - name: SQITCH_TARGET
      value: "db:pg:"
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: ${PREFIX}postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: ${PREFIX}postgres
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          key: database-name
          name: ${PREFIX}postgres
    - name: PGPORT
      value: "5432"
    - name: PGHOST
      value: ${PREFIX}postgres
    - name: SQITCH_FULLNAME
      value: OpenShift Deployer
    - name: SQITCH_EMAIL
      value: deployer@pathfinder.gov.bc.ca

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${PREFIX}schema
  spec:
    replicas: 1
    selector:
      name: ${PREFIX}schema
    strategy:
      type: Recreate
      recreateParams:
        pre:
          failurePolicy: Retry
          execNewPod:
            <<: *envDefaults
            containerName: ${PREFIX}schema
            command:
              - /usr/bin/env
              - bash
              - -c
              - |
                sqitch revert @v1.0.0 -y;
        post:
          failurePolicy: Retry
          execNewPod:
            <<: *envDefaults
            containerName: ${PREFIX}schema
            command:
              - /usr/bin/env
              - bash
              - -c
              - |
                set -euo pipefail;
                sqitch deploy;
    template:
      metadata:
        labels:
          name: ${PREFIX}schema
      spec:
        containers:
        - <<: *envDefaults
          image: ${PREFIX}schema:${GIT_SHA1}
          imagePullPolicy: IfNotPresent
          name: ${PREFIX}schema
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers: []
