apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cas-ggircs-ciip-2018-extract-mirror
  spec:
    lookupPolicy:
      local: true
  status: {}
